export interface DiscountSummary {
  discountId: number;
  accountId: number;
  bundlePromoOverviewId?: number | null;
  bundlePromoHeaderTypeId: number;
  discountCode: string;
  discountName: string;
  bundlePromoDesc?: string | null;
  isFixedAmount: boolean;
  discountPercent?: number | null;
  discountAmount?: number | null;
  priority: number;
  enabled: boolean;
  isAvailable: boolean;
  startDate?: string | null;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  modifiedDate: string;
  modifiedBy: string;
}

export interface UpsertDiscountPayload {
  discountCode: string;
  discountName: string;
  bundlePromoDesc?: string | null;
  bundlePromoHeaderTypeId: number;
  isFixedAmount: boolean;
  discountPercent?: number | null;
  discountAmount?: number | null;
  priority: number;
  enabled: boolean;
  isAvailable: boolean;
  startDate?: string | null;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
}

export interface DiscountShopRule {
  shopId: number;
  shopName: string;
  enabled: boolean;
}

export interface DiscountRuleEditor {
  discountId: number;
  accountId: number;
  bundlePromoOverviewId?: number | null;
  bundlePromoHeaderTypeId: number;
  discountCode: string;
  discountName: string;
  bundlePromoDesc?: string | null;
  priority: number;
  enabled: boolean;
  isAvailable: boolean;
  isDateSpecific: boolean;
  isAutoCalculate: boolean;
  isOpenAmount: boolean;
  isFixedAmount: boolean;
  discountPercent?: number | null;
  discountAmount?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  isNoOtherLoyalty: boolean;
  mandatoryIncludedCategoryIds: number[];
  mandatoryIncludedItemIds: number[];
  mandatoryIncludedModifierItemIds: number[];
  mandatoryExcludedCategoryIds: number[];
  mandatoryExcludedItemIds: number[];
  mandatoryExcludedModifierItemIds: number[];
  priceSpecific?: number | null;
  priceHigherThanEqualToSpecific?: number | null;
  priceLowerThanEqualToSpecific?: number | null;
  isLinkedWithThirdPartyLoyalty: boolean;
  linkedThirdPartyLoyaltyCode?: string | null;
  isAppliedOnItemLevel: boolean;
  upgradeModifierItemId?: number | null;
  discountTag?: string | null;
  discountBenefitModifierAmountAdjustment?: string | null;
  minOrderAmount?: number | null;
  maxOrderAmount?: number | null;
  minMatchedItemAmount?: number | null;
  maxMatchedItemAmount?: number | null;
  minMatchedItemQty?: number | null;
  maxDiscountAmount?: number | null;
  maxDiscountQty?: number | null;
  discountFirstQty?: number | null;
  conditionalDayOfWeeks: string;
  conditionalMonths: string;
  conditionalDates: string;
  conditionalStartDate?: string | null;
  conditionalEndDate?: string | null;
  conditionalStartTime?: string | null;
  conditionalEndTime?: string | null;
  calculateIncludedSubItems: boolean;
  matchMultiple: boolean;
  discountedCategoryIds: number[];
  discountedItemIds: number[];
  discountedModifierItemIds: number[];
  discountedItemPriceOrderDescending: boolean;
  promoHeaderIds: number[];
  shopRules: DiscountShopRule[];
}

export interface UpdateDiscountRuleEditorPayload {
  bundlePromoHeaderTypeId: number;
  discountCode: string;
  discountName: string;
  bundlePromoDesc?: string | null;
  priority: number;
  enabled: boolean;
  isAvailable: boolean;
  isAutoCalculate: boolean;
  isFixedAmount: boolean;
  isOpenAmount: boolean;
  discountPercent?: number | null;
  discountAmount?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  isNoOtherLoyalty: boolean;
  mandatoryIncludedCategoryIds: number[];
  mandatoryIncludedItemIds: number[];
  mandatoryIncludedModifierItemIds: number[];
  mandatoryExcludedCategoryIds: number[];
  mandatoryExcludedItemIds: number[];
  mandatoryExcludedModifierItemIds: number[];
  priceSpecific?: number | null;
  priceHigherThanEqualToSpecific?: number | null;
  priceLowerThanEqualToSpecific?: number | null;
  isLinkedWithThirdPartyLoyalty: boolean;
  linkedThirdPartyLoyaltyCode?: string | null;
  isAppliedOnItemLevel: boolean;
  upgradeModifierItemId?: number | null;
  discountTag?: string | null;
  discountBenefitModifierAmountAdjustment?: string | null;
  minOrderAmount?: number | null;
  maxOrderAmount?: number | null;
  minMatchedItemAmount?: number | null;
  maxMatchedItemAmount?: number | null;
  minMatchedItemQty?: number | null;
  maxDiscountAmount?: number | null;
  maxDiscountQty?: number | null;
  discountFirstQty?: number | null;
  conditionalDayOfWeeks?: string | null;
  conditionalMonths?: string | null;
  conditionalDates?: string | null;
  conditionalStartDate?: string | null;
  conditionalEndDate?: string | null;
  conditionalStartTime?: string | null;
  conditionalEndTime?: string | null;
  calculateIncludedSubItems: boolean;
  matchMultiple: boolean;
  discountedCategoryIds: number[];
  discountedItemIds: number[];
  discountedModifierItemIds: number[];
  discountedItemPriceOrderDescending: boolean;
  promoHeaderIds: number[];
  shopRules: DiscountShopRule[];
}
